# site properties and page defaults
title: Mathieson Lab
subtitle: 
description: We are a computational lab focusing on developing machine learning algorithms for biological data. Currently we are working on inference tasks related to natural selection and demographic inference, as well as generative models for genomic data from humans, mosquitos, and other species.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: smathi@sas.upenn.edu
  orcid: 0000-0002-0484-0838
  google-scholar: ETJoidYAAAAJ
  github: saramathieson

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
